### ISSUE TITLE
Error: 'Options' object has no attribute 'model_dump'

### ISSUE THREAD

**Issue by shiyongxin** [taketwo/llm-ollama#6] opened 2024-05-20 14:19 UTC
% llm -m llama3 "How much is 2+2?"
Error: 'Options' object has no attribute 'model_dump'

**Comment by taketwo** [comment] 2024-05-20 17:18
Hey @Taik, looks like there is an issue with the code we recently merged. Do you have any clue what may be the reason?

**Comment by taketwo** [comment] 2024-05-21 19:51
By the way, I cannot reproduce this with the latest versions of packages:
* `llm==0.14`
* `llm-ollama==0.3.0` 
* `ollama==0.1.38`

**Comment by Taik** [comment] 2024-05-21 22:39
Ah - sorry about this; I didn't test with a clean env. I believe this is because of pydantic. Will send a PR to fix this shortly.

**Closed** 2024-05-22 07:08 UTC

**Comment by taketwo** [comment] 2024-05-22 07:15
@shiyongxin I've tagged a new release. Please run `llm install --upgrade llm-ollama` to get the fix.
